get:
  tags:
    - Subscriptions
    - Telco
  summary: Get service settings
  produces:
    - application/json
  parameters:
    - $ref: "#/parameters/authorization"
    - name: id
      in: path
      description: id of subscription to fetch the settings for
      required: true
      type: string
  responses:
    200:
      description: Returns service settings
      schema:
        $ref: '#/definitions/SubscriptionServiceSettings'
    401:
      description: unauthorized
      schema:
        $ref: '#/definitions/Status'
put:
  tags:
    - Subscriptions
    - Telco
  summary: Update service settings
  description: Unspecified services will not be changed
  consumes:
    - application/json
  parameters:
    - $ref: "#/parameters/authorization"
    - name: id
      in: path
      description: id of subscription to update the settings for
      required: true
      type: string
    - name: settings
      in: body
      description: settings to write
      schema:
        type: array
        items:
          $ref: '#/definitions/SubscriptionServiceSettingsChangeRequest'
  responses:
    204:
      description: Invoicing settings updated
    401:
      description: unauthorized
      schema:
        $ref: '#/definitions/Status'
